#配置datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.18.130:3306/springboot?serverTimezone=UTC、
    url: jdbc:mysql://127.0.0.1:3306/hmybaytis?serverTimezone=UTC
    username: root
    password: root
  redis:
    #配置redis0
    database: 0
#    host: 192.168.186.130
    host: 127.0.0.1
    port: 6379

    timeout: 3000       # 连接超时时间 单位 ms（毫秒）
    pool:
      max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
      min-idle: 0       # 连接池中的最小空闲连接，默认值也是0
      max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出

  #开启隐藏方法过滤器，识别put和delete请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true
